Refactoring Hooks and Accessibility Test Suite from JS to TS
oslabs-beta/spearmint pull request #23
Opened 2021-03-22 20:21 UTC by sharon-zhu

### The following changes took place: 

- Hook Action Types get updated from optional to strictly typed
- Accessibility related JS files renamed to TS files 
- accTypes file updated to reflect correct interfaces 
- Accessibility components typed where necessary 
- Accessibility reducer and action type files strictly typed. 
                                   
### Files altered:
```
| src/components/ReactTestComponent/DescribeRenderer/DescribeRenderer.jsx
| src/components/TestCase/AccTestCase.jsx     
      | /AccTestComponent/ItRenderer/ItRenderer.tsx    
| src/components/TestMenu/AccTestMenu.tsx
| src/context/actions/accTestCaseActions.js          
| src/context/reducers/accTestCaseReducer.js
| src/context/reducers/hooksTestCaseReducer.ts          
| src/utils/hooksTypes.ts 
| src/utils/accTypes.ts 
```

2021-03-22 22:53 UTC, taoantaoan approved these changes
Thanks for taking this all on Sharon! Amazing.

Looks good. No major concerns. As per discussed double check the conversion of 'const describeId = Number(e.target.id);' Might also remove some of the code that is commented out.

2021-03-22 23:02 UTC, annieshinn requested changes
Hi Sharon!

Thank you so much for your hard work on this PR! I've noted some things throughout the code. I look forward to working with you to resolve it all. 😄

2021-03-22 23:02 UTC, annieshinn commented on src/utils/endpointTypes.ts
> +
Could we review this file again as a team? I'm not sure what changed.

2021-03-22 23:02 UTC, annieshinn commented on src/utils/accTypes.ts
> +  describeId: number;
May we code review this file again? Thank you!

2021-03-23 23:52 UTC, sharon-zhu commented on src/context/reducers/hooksTestCaseReducer.ts
> +  hookFilePath: '',
Resolve TS error. The HooksTestCaseState that this object is typed to has hookFileName and hookFilePath properties. These properties used to be added when a file became associated. Now the property is initially added as an empty string.

2021-03-23 23:52 UTC, sharon-zhu commented on src/utils/endpointTypes.ts
> +
Looks to be an extra line just from moving around the file. I'll delete.

2021-03-24 00:01 UTC, annieshinn commented on src/context/reducers/hooksTestCaseReducer.ts
> +  hookFilePath: '',
Thanks for the explanation!

2021-03-24 00:01 UTC, annieshinn commented on src/utils/endpointTypes.ts
> +
Oh, I don't have issues with the line, just confused with the whole file in general.

2021-03-24 03:34 UTC, annieshinn commented on src/utils/endpointTypes.ts
> +
NVM thank you!

2021-03-24 03:44 UTC, taoantaoan approved these changes

2021-03-24 03:50 UTC, annieshinn approved these changes
Thanks for implementing all of these changes, Sharon. Everything looks fantastic!

2021-03-24 03:50 UTC, merged