Testing the Spearmint Application for Accessibility
oslabs-beta/spearmint pull request #24
Opened 2021-03-23 18:14 UTC by astaiglesia

![Screenshot from 2021-03-23 11-11-57](https://user-images.githubusercontent.com/75825642/112196882-b6b57f00-8bc8-11eb-8170-8ca2ba50da48.png)  
# Accessibility Testing of the Spearmint Application                                            

This pull request covers the addition of accessibility testing for the Spearmint application itself. Two tests were created utilizing Spectron's testing framework to leverage webdriverIO allowing Chromium based automation of the Spearmint application. 

Node Integration allows both test scripts to access core Electron API's to run mocha, with the assertion library chai, chai as promised along with Google's Accessibility Developer Tools library to run an accessibility audit on the targeted electron.js and package.json. The tests as configured utilize the Application API to automate instannces of Electron running Spearmint for every integration and end to end tests that may be run. Audit results render in the IDE terminal to be addressed  by the developer.

<br>

### Integration Test Results

![integration accessibility audit](https://user-images.githubusercontent.com/75825642/112190201-02b0f580-8bc2-11eb-9554-0b2901d1ae13.png)

<br>

### End to End Test Results

![e2e accessibility audit](https://user-images.githubusercontent.com/75825642/112190127-f2007f80-8bc1-11eb-9e1c-6cc5cac02c73.png)

<br>

The issues noted by the initial audits above have been addressd along with those identified by manual testing against WCAG Standards. These changes include: 

- Providing a descriptive title element enabling a user to know the topic of a page without viewing the DOM. This addresses Googles Accessibility DevTool standard 'AX_TITLE_01' and has been implemented with reference to MDN documentation's discussion on 'Acessibility concerns' for this element. 

<p> <em> "A common navigation technique for users of assistive technology is to read the page title and infer the content the page contains." </em>

![newTitle](https://user-images.githubusercontent.com/75825642/112190982-c5009c80-8bc2-11eb-989d-c461f6d391e7.png)

<br>

- Providing greater contrasts between font and background colors through the website as well as including a descriptive tagline. HTML structure and Sass styling have been edited for the updated user interface and experience.

<p>  <em> “WCAG (Web Content Accessibility Guidelines) ensure that content is accessible by everyone, regardless of disability or user device. To meet these standards, text and interactive elements should have a color contrast ratio of at least 4.5:1. This ensures that viewers who cannot see the full color spectrum are able to read the text.” </em>

![newMenu](https://user-images.githubusercontent.com/75825642/112191051-d6e23f80-8bc2-11eb-85be-aadb07aab4bf.png)
![newTestSuite](https://user-images.githubusercontent.com/75825642/112191070-dcd82080-8bc2-11eb-9277-ff26be2b30be.png)

These changes allow Spearmint to now deliver an accessibility compliant contrast ratio of 4.71:1.

<br>

Additional tests may be created by future developers to expand scope coverage.

<hr>

## Files Created and Modified

```
| package.json
	| public/index.html
	| src/__tests__/spec.e2e.js
	| src/__tests__/spec.integra.js 
	| src/assets/stylesheets/colors.scss
	| src/pages/ProjectLoader/ProjectLoader.jsx
	| src/pages/ProjectLoader/ProjectLoader.module.scss
| tsconfig.json

```

<br>
<hr>

## Known Bug

- The corrected error still elicits an error response on re-test

<br>
<hr>

## Links to Docs

[Spectron](https://www.npmjs.com/package/spectron)

[Spectron - Accessibility](https://github.com/electron-userland/spectron#accessibility-testing)

[Electron - Accessibility](https://www.electronjs.org/docs/tutorial/accessibility)

[Chrome Accessibility Developer Tools](https://github.com/GoogleChrome/accessibility-developer-tools)

[Accessibility Dev Tools - #ax_title_01](https://github.com/GoogleChrome/accessibility-developer-tools/wiki/Audit-Rules#ax_title_01)

[MDN - Title Element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title)

[Mocha Testing Framework](https://mochajs.org/)

[Chai Assertion Library](https://www.chaijs.com/api/)

[Chai Assertions for Promises](https://www.npmjs.com/package/chai-as-promised)

<hr>

### Contributing Members

Co-authored-by: Gabriel Christo 45021525+bielchristo@users.noreply.github.com

Co-authored-by: Alfred Sta. Iglesia 75825642+astaiglesia@users.noreply.github.com

2021-03-23 22:12 UTC, taoantaoan requested changes
Great work, Alfred! This looks great. You've done a great job in implementing this.

Any chance we could double check ProjectLoader.module.scss? I wonder if there might be a couple of stray comments that we could clean up.

2021-03-24 02:51 UTC, annieshinn requested changes
Hey Alfred!

As we discussed at code review, let's refactor the e2e test and bring it back to the full group! I made some comments throughout for you to look at as well. Thanks for your hard work Alfred!

Annie

2021-03-24 02:51 UTC, annieshinn commented on src/__tests__/spec.e2e.js
> +const Application = require('spectron').Application;
Let's think about async in this file as discussed.

2021-03-24 02:51 UTC, annieshinn commented on src/pages/ProjectLoader/ProjectLoader.jsx
> +        <span id={styles.purpose}>simply testing your react application</span>
Why were all these stylistic changes (indentation, removing spaces) made in this file?

2021-03-24 02:52 UTC, annieshinn commented on src/pages/ProjectLoader/ProjectLoader.jsx
> +        <span id={styles.purpose}>simply testing your react application</span>
If unnecessary, please revert! I think the old way seems accurate :)

2021-03-24 04:24 UTC, astaiglesia commented on tsconfig.json
> +, "tests/spec.integra.js"  ]
Fixed

2021-03-24 04:25 UTC, astaiglesia commented on src/pages/ProjectLoader/ProjectLoader.module.scss
> +  // border: thin solid red;
comments have been removed!

2021-03-24 04:26 UTC, astaiglesia commented on src/__tests__/spec.e2e.js
> +const Application = require('spectron').Application;
async issue has been addressed

2021-03-24 04:39 UTC, astaiglesia commented on src/pages/ProjectLoader/ProjectLoader.jsx
> +        <span id={styles.purpose}>simply testing your react application</span>
Changes addressed as discussed =)

2021-03-24 04:51 UTC, annieshinn approved these changes
Thanks for implementing all of the changes we discussed! You're a star! ⭐ I look forward to code review in the morning, especially to learn about the new and improved test files.

Thanks Alfred!
Annie

2021-03-24 17:33 UTC, annieshinn commented on src/__tests__/spec.e2e.js
> +const Application = require('spectron').Application;
Thanks! Would love to hear about how you fixed it at code review :)

2021-03-24 17:34 UTC, annieshinn approved these changes
Looks good. Tests on my machine seem to function as expected. Thanks Alfred!

2021-03-24 18:08 UTC, taoantaoan approved these changes

2021-03-24 18:08 UTC, taoantaoan commented on src/pages/ProjectLoader/ProjectLoader.module.scss
> +  // border: thin solid red;
Can we remove this comment: '// border: thin solid red;' ?

2021-03-24 18:08 UTC, taoantaoan commented on src/pages/ProjectLoader/ProjectLoader.module.scss
> +  // border: thin solid blue;
Might we be able to remove these comments?

2021-03-24 18:08 UTC, taoantaoan commented on src/pages/ProjectLoader/ProjectLoader.module.scss
> +  // border: thin solid red;
Can we remove this comment?

2021-03-24 18:14 UTC, taoantaoan approved these changes

2021-03-24 18:15 UTC, sharon-zhu approved these changes
Thanks for the updates! Filed pulled down and tests run well.

2021-03-24 18:17 UTC, astaiglesia commented on src/pages/ProjectLoader/ProjectLoader.module.scss
> +  // border: thin solid red;
got it covered!

2021-03-24 18:17 UTC, merged

2021-03-24 18:17 UTC, astaiglesia commented on src/pages/ProjectLoader/ProjectLoader.module.scss
> +  // border: thin solid blue;
removed!

2021-03-24 18:17 UTC, astaiglesia commented on src/pages/ProjectLoader/ProjectLoader.module.scss
> +  // border: thin solid red;
this was addressed. thanks~