Fixing tests
oslabs-beta/spearmint pull request #3
Opened 2022-01-26 01:02 UTC by chloelu29

- fixed tests import path in general 
- fixed database import path in endpoint testing 
- fixed export files in puppeteer

2022-01-26 18:24 UTC, Ruzeb requested changes

2022-01-26 18:24 UTC, Ruzeb commented on public/electron.jsx
> +    console.log('filePath:', filePath)
remove console logs

2022-01-26 18:24 UTC, Ruzeb commented on src/components/TestMenu/EndpointTestMenu.tsx
> +    console.log('endpointTestCase:', endpointTestCase);
remove

2022-01-26 18:24 UTC, Ruzeb commented on src/context/useGenerateTest.jsx
> +        console.log('filepath before replace', filePath)
remove

2022-01-26 18:24 UTC, Ruzeb commented on src/context/useGenerateTest.jsx
> +
remove

2022-01-26 20:53 UTC, Ruzeb approved these changes
lgtm

2022-01-27 00:14 UTC, alsdk850 commented on src/context/useGenerateTest.jsx
> +      console.log('createPathtoHooks statement:', statement);
delete!

2022-01-27 00:14 UTC, alsdk850 commented on src/context/useGenerateTest.jsx
> +        console.log('hooksTestCase:', hooksTestCase)
delete console!

2022-01-27 00:14 UTC, alsdk850 commented on src/context/useGenerateTest.jsx
> +        console.log('in hooksTestCase OBJECT:', hooksTestCase)
delete console

2022-01-27 00:15 UTC, alsdk850 requested changes

2022-01-27 00:15 UTC, alsdk850 commented on src/context/useGenerateTest.jsx
> +      console.log('createPathtoHooks statement:', statement);
s

2022-01-27 00:24 UTC, alsdk850 approved these changes

2022-01-27 00:24 UTC, merged