Update save
oslabs-beta/spearmint pull request #7
Opened 2022-02-04 19:38 UTC by huyqbui

Chloe and I created save test buttons for each of the test menus (except security testing). 

The Save Test button on click will: 
  - Open export file modal if user has not save the test file yet
  - Overwrite and save the current test file on successive clicks

Added styling to match the neighboring button components for uniformity.

2022-02-04 19:47 UTC, alsdk850 requested changes
Great job Chloe and Huy! 😄

2022-02-04 19:47 UTC, alsdk850 commented on public/electron.jsx
> +  console.log('opening github oauth window');
console.log is here!

2022-02-04 19:47 UTC, alsdk850 commented on src/pages/TestFile/TestFile.jsx
> +  // const saveTest = () => {
maybe delete this whole comment block if not used?🤔

2022-02-04 19:47 UTC, alsdk850 commented on src/pages/TestFile/TestFile.jsx
> +      {/* <br></br>
Same with this one maybe we could delete this chunk of comment if it isn't necessary?!

2022-02-04 20:13 UTC, huyqbui commented on public/electron.jsx
> +  console.log('opening github oauth window');
nice catch! removing it now

2022-02-04 20:14 UTC, huyqbui commented on src/pages/TestFile/TestFile.jsx
> +  // const saveTest = () => {
forgot about these, removing them now

2022-02-04 20:14 UTC, huyqbui commented on src/pages/TestFile/TestFile.jsx
> +      {/* <br></br>
got it, removing it now!

2022-02-04 20:44 UTC, alsdk850 approved these changes

2022-02-09 03:28 UTC, Ruzeb approved these changes
LGTM

2022-02-09 15:39 UTC, merged